IvyshineGui.SetFont("s10 Norm cBlack", "Calibri")
;IvyshineGui.Add("Picture", "xs+201 y36 w323 h175 Section", "C:\Users\ray20\Downloads\fields horizontal - copy.png")
;IvyshineGui.Add("Picture", "xs+201 y36 w323 h175 Section", "HBITMAP:" Gdip_CreateHBITMAPFromBitmap(Gdip_CreateBitmapFromFile("C:\Users\ray20\Downloads\fields horizontal - copy.png")))
;MsgBox(Gdip_CreateBitmapFromFile("C:\Users\ray20\Downloads\fields horizontal - copy.png"))
IvyshineGui.SetFont()
IvyshineGui.SetFont("s8", "Calibri")